"""story author_id and status

Revision ID: c2d934a24eee
Revises: e3a531c1ff09
Create Date: 2026-09-19 00:44:31.331873

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'c2d934a24eee'
down_revision: Union[str, None] = 'e3a531c1ff09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('origin_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'origin_url')
    # ### end Alembic commands ###
