"""add community

Revision ID: e3a531c1ff09
Revises: 1ac61f178ab3
Create Date: 2026-09-18 13:31:33.689895

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'e3a531c1ff09'
down_revision: Union[str, None] = '1ac61f178ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
