"""add interactions

Revision ID: eedb8efa55ae
Revises: 9d89c9d81bce
Create Date: 2026-09-29 21:44:27.085855

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'eedb8efa55ae'
down_revision: Union[str, None] = '9d89c9d81bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
